### ISSUE TITLE
lain build error

### ISSUE THREAD

**Issue by liuxu623** [laincloud/lain-cli#25]
```
➜  hello-world git:(master) lain build
>>> Building meta and release images ...
Traceback (most recent call last):
  File "/usr/local/bin/lain", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/lain_cli/lain.py", line 67, in main
    parser.dispatch()
  File "/usr/local/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/local/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/local/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/usr/local/lib/python2.7/site-packages/lain_cli/build.py", line 20, in build
    yml = lain_yaml()
  File "/usr/local/lib/python2.7/site-packages/lain_cli/utils.py", line 57, in lain_yaml
    return LainYaml(LAIN_YAML_PATH, ignore_prepare=ignore_prepare)
  File "/usr/local/lib/python2.7/site-packages/lain_sdk/lain_yaml.py", line 37, in __init__
    self.init_act(self.yaml_path, ignore_prepare=ignore_prepare)
  File "/usr/local/lib/python2.7/site-packages/lain_sdk/lain_yaml.py", line 50, in init_act
    self._prepare_act(ignore_prepare=ignore_prepare)
  File "/usr/local/lib/python2.7/site-packages/lain_sdk/lain_yaml.py", line 371, in _prepare_act
    shared_prepare_image_name = self.ensure_proper_shared_image()
  File "/usr/local/lib/python2.7/site-packages/lain_sdk/lain_yaml.py", line 104, in ensure_proper_shared_image
    local_images = self._get_prepare_shared_image_names(False).items()
  File "/usr/local/lib/python2.7/site-packages/lain_sdk/lain_yaml.py", line 68, in _get_prepare_shared_image_names
    registry, self.appname)
  File "/usr/local/lib/python2.7/site-packages/lain_sdk/mydocker.py", line 320, in get_tag_list_in_docker_daemon
    c = Client()
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 56, in __init__
    self._auth_configs = auth.load_config()
  File "/usr/local/lib/python2.7/site-packages/docker/auth/auth.py", line 188, in load_config
    res.update(parse_auth(data['auths'], raise_on_error=True))
  File "/usr/local/lib/python2.7/site-packages/docker/auth/auth.py", line 130, in parse_auth
    'Invalid configuration for registry {0}'.format(registry)
docker.errors.InvalidConfigFile: Invalid configuration for registry registry.aliyuncs.com
```

**Comment by bibaijin** [comment]
@liuxu623 这是因为 lain-sdk 使用的老的 docker-py，无法解析 ${HOME}/.docker/config.json 文件，已在 https://github.com/laincloud/lain-sdk/pull/19 中修复。可以执行以下步骤测试：

```
# 升级 lain-cli 之前
docker login registry.aliyuncs.com
cd ${lain-app-project}
lain build  # 应该会看到上文所述的错误

# 升级 lain-cli
pip install --upgrade lain-cli
cd ${lain-app-project}
lain build  # 应该可以正常编译
```

**Comment by bibaijin** [comment]
@liuxu623 @fossilet 我用 docker 替代了 docker-py，而 `docker` 与 `docker-py` 冲突。如果主机上装过 docker-py 的话依然会出现错误，需要先 `pip uninstall docker-py`。
